name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test
